import { locale } from '../../i18n';

const tr = {
  title: 'İlk kütüphaneni hazırla',
  subtitle: 'Kaynağını bağla, erişimi kontrol et ve ilk taramanı başlat.',
  source: 'Kaynak seç',
  details: 'Erişimi doğrula',
  review: 'Kaynağı oluştur',
  scan: 'İlk tarama',
  local: 'Yerel klasör',
  localHint: 'Sunucuya bağlı bir disk veya Docker içine bağlanmış medya klasörü.',
  drive: 'Google Drive',
  driveHint: 'Bağlı Google hesabındaki bir klasör. Dosyalar Drive üzerinde kalır.',
  next: 'Devam et',
  back: 'Geri',
  later: 'Daha sonra',
  settings: 'Kaynak ayarlarına dön',
  name: 'Kütüphane adı',
  path: 'Sunucudaki klasör yolu',
  folder: 'Drive klasör kimliği',
  account: 'Google hesabı',
  pathHint:
    'Bilgisayarındaki değil, sunucunun gördüğü mutlak yolu kullan. Docker için medya klasörünü salt okunur bağla (ör. /media/films).',
  folderHint:
    'Drive klasörü bağlantısındaki /folders/ sonrasındaki kimliği gir. Bu sihirbaz yalnızca seçtiğin klasörü ekler.',
  connect: 'Google hesabını bağla',
  connectHint: 'Bağlantı yeni sekmede açılır. İşlem bitince buraya dönüp hesap listesini yenile.',
  refresh: 'Yeniden dene',
  refreshAccounts: 'Hesapları yenile',
  select: 'Hesap seç',
  verify: 'Erişimi kontrol et',
  verified: 'Erişim doğrulandı',
  shallow:
    'Bu kontrol klasör erişimini doğrular. Medya dosyaları ilk taramada incelenir; alt klasörlerde ayrıca hata olabilir.',
  create: 'Kaynağı oluştur',
  creating: 'Oluşturuluyor…',
  busy: 'Kontrol ediliyor…',
  createHint:
    'Henüz tarama yapılmayacak. Kaynak oluşturulduktan sonra taramayı ayrıca başlatabilirsin.',
  start: 'Taramayı başlat',
  retry: 'Tekrar tara',
  running: 'Tarama devam ediyor',
  completed: 'Tarama tamamlandı',
  failed: 'Tarama tamamlanamadı',
  waiting: 'Kaynak hazır',
  waitHint: 'İlk tarama henüz başlamadı. Bu sayfanın bağlantısıyla daha sonra devam edebilirsin.',
  progressHint:
    'Tarama sunucuda devam eder; bu sayfayı açık tutman gerekmez. Dosyalar silinmez veya taşınmaz.',
  counts: (added: number, updated: number, errors: number) =>
    `${added} eklendi · ${updated} güncellendi · ${errors} hata`,
  empty:
    'Yeni medya eklenmedi. Klasör içeriğini, desteklenen dosya türlerini ve erişim izinlerini kontrol et.',
  warnings:
    'Bazı dosyalar işlenemedi. Ayrıntıları kaynak ayarlarındaki tarama geçmişinden inceleyebilirsin.',
  browse: 'Kütüphaneye git',
  music: 'Müziklere git',
  loadError: 'Kurulum bilgileri yüklenemedi.',
  accessError: 'Erişim doğrulanamadı. Klasör yolunu veya Google bağlantısını kontrol et.',
  createError:
    'Kaynak oluşturulamadı. Yeniden denemeden önce kaynak ayarlarında oluşup oluşmadığını kontrol et.',
  scanError: 'Tarama başlatılamadı. Kaynak kaydedildi; yeniden deneyebilirsin.',
  admin: 'Kaynak kurulumu için yönetici hesabıyla giriş yap.',
  missing: 'Bu kaynak bulunamadı veya erişim yetkin yok.',
  resume: 'Kaydedilmiş kaynaktan devam et',
  resumeHint: 'Yeni kaynak oluşturmadan mevcut kaynağın taramasına dönebilirsin.',
};
const en: typeof tr = {
  title: 'Set up your first library',
  subtitle: 'Connect a source, check access and start your first scan.',
  source: 'Choose a source',
  details: 'Check access',
  review: 'Create source',
  scan: 'First scan',
  local: 'Local folder',
  localHint: 'A disk attached to your server or a media folder mounted into Docker.',
  drive: 'Google Drive',
  driveHint: 'A folder in a connected Google account. Files stay on Drive.',
  next: 'Continue',
  back: 'Back',
  later: 'Do this later',
  settings: 'Back to source settings',
  name: 'Library name',
  path: 'Folder path on the server',
  folder: 'Drive folder ID',
  account: 'Google account',
  pathHint:
    'Use the absolute path visible to the server, not your computer. Mount media read-only in Docker (e.g. /media/films).',
  folderHint:
    'Enter the ID after /folders/ in the Drive folder link. This wizard only adds the selected folder.',
  connect: 'Connect a Google account',
  connectHint:
    'The connection opens in a new tab. Return here and refresh the accounts when finished.',
  refresh: 'Try again',
  refreshAccounts: 'Refresh accounts',
  select: 'Choose an account',
  verify: 'Check access',
  verified: 'Access verified',
  shallow:
    'This checks folder access. Media is examined during the first scan; subfolders may still have access errors.',
  create: 'Create source',
  creating: 'Creating…',
  busy: 'Checking…',
  createHint: 'No scan will run yet. You can start it separately after creating the source.',
  start: 'Start scan',
  retry: 'Scan again',
  running: 'Scan in progress',
  completed: 'Scan complete',
  failed: 'Scan did not complete',
  waiting: 'Source ready',
  waitHint: 'The first scan has not started. You can resume later using this page’s link.',
  progressHint:
    'Scanning continues on the server; you can leave this page. Files are not deleted or moved.',
  counts: (added, updated, errors) => `${added} added · ${updated} updated · ${errors} errors`,
  empty:
    'No new media was added. Check the folder contents, supported file types and access permissions.',
  warnings:
    'Some files could not be processed. Review scan history in source settings for details.',
  browse: 'Browse library',
  music: 'Browse music',
  loadError: 'Could not load setup information.',
  accessError: 'Could not verify access. Check the folder path or Google connection.',
  createError:
    'Could not create the source. Check source settings before retrying in case it was already created.',
  scanError: 'Could not start the scan. Your source is saved; you can retry.',
  admin: 'Sign in as an administrator to set up sources.',
  missing: 'This source was not found or you do not have access.',
  resume: 'Resume a saved source',
  resumeHint: 'Return to scanning an existing source without creating another one.',
};
export const copy = locale === 'en' ? en : tr;
